Repository swarnade/webdesign-switch, pull requests merged in 2024-02, with the labels that each got.

#153 feedback ui changed
  css/fdback.css
  feedback.html
Labels: Easy, JWOC

#157 Add neumorphism button completed #147
  design_button/vishal.css
  index.html
Labels: Easy, JWOC

#179 8 buttons
  design_button/rimi1.css
  design_button/rimi2.css
  design_button/rimi3.css
  design_button/rimi4.css
  design_button/rimi5.css
  design_button/rimi6.css
  design_button/rimi7.css
  design_button/rimi8.css
  index.html
Labels: Hard, JWOC

#180 Added 8 buttons as a contribution under JWOC'24
  .vscode/settings.json
  design_button/SuvayuN-1.css
  design_button/SuvayuN-2.css
  design_button/SuvayuN-3.css
  design_button/SuvayuN-4.css
  design_button/SuvayuN-5.css
  design_button/SuvayuN-6.css
  design_button/SuvayuN-7.css
  design_button/SuvayuN-8.css
  index.html
Labels: Hard, JWOC

#175 Added light and dark mode functionality for issue #161
  assets/moon.png
  assets/sun.png
  css/main.css
  design_button/Sanglap-Halder.css
  index.html
Labels: Medium, JWOC

#189 Added customised scrollbar
  css/main.css
Labels: Medium, JWOC

#194 #190 fixed the issue
  design_button/shahilaf_01.css
  footer_main.css
  index.html
Labels: Medium, JWOC

#184 changed menu icon to cross icon
  assets/cross.jpg
  assets/menu.svg
  index.html
Labels: Easy, JWOC

#186 Customized search field
  css/main.css
  index.html
Labels: Medium, JWOC

#198 8 buttons
  design_button/rimi10.css
  design_button/rimi11.css
  design_button/rimi12.css
  design_button/rimi9.css
  index.html
Labels: Hard, JWOC

#204 completion of info page
  index.html
Labels: Hard, JWOC

#205 8 new buttons added
  design_button/RatnojitSaha-24.css
  design_button/RatnojitSaha-25.css
  design_button/RatnojitSaha-26.css
  design_button/RatnojitSaha-27.css
  design_button/RatnojitSaha-28.css
  design_button/RatnojitSaha-29.css
  design_button/RatnojitSaha-30.css
  design_button/RatnojitSaha-31.css
  index.html
Labels: Hard, JWOC
