Repository swarnade/webdesign-switch, pull requests merged in 2024-01, with the labels that each got.

#46 Changed CSS of boxes and added 2 new button styles
  design_button/ayesha-1.css
  design_button/ayesha-2.css
  design_button/full.css
  index.html
Labels: Easy, JWOC

#56 ADD:Add Fav-icon and nav-icon
  .vscode/settings.json
  FavIcon.png
  index.html
Labels: Medium, JWOC

#52 changed the look of nav bar and toggler
  css/main.css
  index.html
Labels: Medium, JWOC

#45 added a new button
  design_button/krittika2004.css
  index.html
Labels: Easy, JWOC

#96 Redesign Simple Minimalist Navbar
  css/main.css
Labels: Hard, JWOC

#102 fixed height ui issue
  design_button/shahilaf_01.css
  index.html
Labels: Medium, JWOC

#103 made the page responsive
  css/main.css
Labels: Medium, JWOC

#107 Add a New Button
  design_button/ASIF-MANDAL.css
  heelo.html
Labels: Easy, JWOC

#116 Added Scroll Animations
  .vscode/settings.json
  css/main.css
  index.html
Labels: Medium, JWOC

#146 New 5 buttons added with a footer in main page
  css/main.css
  design_button/RatnojitSaha-11.css
  design_button/RatnojitSaha-12.css
  design_button/RatnojitSaha-13.css
  design_button/RatnojitSaha-14.css
  design_button/RatnojitSaha-15.css
  footer_main.css
  index.html
Labels: Hard, JWOC

#149 Added responsive hamburger menu to info page
  infopage/index.html
  infopage/style.css
Labels: Medium, JWOC
